services:
  sshfs-mount:
    image: pschmucker/sshfs-mount:latest
    container_name: sshfs-mount
    restart: unless-stopped
    stop_grace_period: 30s
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - ${SSHFS_PRIVATE_KEY_PATH}:/root/.ssh/id_rsa:ro
      - type: bind
        source: ${SSHFS_MOUNT_PATH}
        target: /mnt/sshfs
        bind:
          propagation: rshared
    environment:
      - SSHFS_REMOTE_XXX_NAME=${XXX_NAME}
      - SSHFS_REMOTE_XXX_USERNAME=${XXX_USERNAME}
      - SSHFS_REMOTE_XXX_HOST=${XXX_HOST}
      - SSHFS_REMOTE_XXX_PATH=${XXX_PATH}
      - SSHFS_REMOTE_XXX_UID=${XXX_UID}
      - SSHFS_REMOTE_XXX_GID=${XXX_GID}

      - SSHFS_REMOTE_YYY_NAME=${YYY_NAME}
      - SSHFS_REMOTE_YYY_USERNAME=${YYY_USERNAME}
      - SSHFS_REMOTE_YYY_HOST=${YYY_HOST}
      - SSHFS_REMOTE_YYY_PATH=${YYY_PATH}
      - SSHFS_REMOTE_YYY_UID=${YYY_UID}
      - SSHFS_REMOTE_YYY_GID=${YYY_GID}
      
      - SSHFS_REMOTE_ZZZ_NAME=${ZZZ_NAME}
      - SSHFS_REMOTE_ZZZ_USERNAME=${ZZZ_USERNAME}
      - SSHFS_REMOTE_ZZZ_HOST=${ZZZ_HOST}
      - SSHFS_REMOTE_ZZZ_PATH=${ZZZ_PATH}
      - SSHFS_REMOTE_ZZZ_UID=${ZZZ_UID}
      - SSHFS_REMOTE_ZZZ_GID=${ZZZ_GID}

networks:
  default:
    name: sshfs-mount
